# Generated by Django 6.0.5 on 2026-05-13 17:45

import trim.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(default=trim.models.generate_short_code, max_length=30, unique=True),
        ),
    ]
